#!/bin/sh
# The runtime role must not be a superuser, otherwise every RLS policy is bypassed (§7.2).
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cbi_app') THEN
    CREATE ROLE cbi_app LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE
      PASSWORD '${APP_DB_PASSWORD}';
  ELSE
    ALTER ROLE cbi_app WITH PASSWORD '${APP_DB_PASSWORD}' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO cbi_app;
GRANT USAGE ON SCHEMA public TO cbi_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cbi_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cbi_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cbi_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO cbi_app;
SQL
