import { useEffect, useState } from "react";
import { fmt, request } from "../api";
import { ErrorBox, Loading } from "../components/Widgets";

interface Settings { gateway_enabled:boolean; zarinpal_sandbox:boolean; merchant_id_configured:boolean; merchant_id_hint:string; custom_credit_price_per_minute_toman:number; installation_initial_toman:number; installation_reinstall_toman:number; installation_dedicated_toman:number; renewal_lead_days:number; terms_version:string; terms_url:string; tax_percent:number; automatic_discounts_enabled:boolean }

export default function CommerceSettings(){
  const[value,setValue]=useState<Settings|null>(null);const[merchant,setMerchant]=useState("");const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
  useEffect(()=>{request<Settings>("/v1/admin/commerce/settings").then(setValue).catch(reason=>setError(reason.message));},[]);
  if(!value)return error?<ErrorBox message={error}/>:<Loading/>;
  async function save(event:React.FormEvent){event.preventDefault();try{const body:Record<string,unknown>={...value};delete body.merchant_id_configured;delete body.merchant_id_hint;if(merchant.trim())body.zarinpal_merchant_id=merchant.trim();setValue(await request<Settings>("/v1/admin/commerce/settings",{method:"PATCH",body}));setMerchant("");setNotice("تنظیمات ذخیره شد.");}catch(reason){setError((reason as Error).message);}}
  const numericKeys = [['custom_credit_price_per_minute_toman','قیمت هر دقیقه اعتبار'],['installation_initial_toman','هزینه نصب اولیه'],['installation_reinstall_toman','هزینه نصب مجدد'],['installation_dedicated_toman','هزینه استقرار اختصاصی'],['renewal_lead_days','روزهای پیش‌هشدار تمدید'],['tax_percent','درصد مالیات']] as const;
  return <form className="max-w-3xl space-y-4" onSubmit={save}><div><h1 className="text-2xl font-bold">تنظیمات تجاری</h1><p className="mt-1 text-sm text-slate-500">مبالغ داخلی تومان هستند و تبدیل ریال فقط در adapter درگاه انجام می‌شود.</p></div><ErrorBox message={error}/>{notice?<div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>:null}<section className="card grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2"><input type="checkbox" checked={value.gateway_enabled} onChange={event=>setValue({...value,gateway_enabled:event.target.checked})}/>درگاه فعال باشد</label><label className="flex items-center gap-2"><input type="checkbox" checked={value.zarinpal_sandbox} onChange={event=>setValue({...value,zarinpal_sandbox:event.target.checked})}/>حالت sandbox</label><div className="md:col-span-2"><label className="label">Merchant ID</label><input className="input" dir="ltr" type="password" value={merchant} onChange={event=>setMerchant(event.target.value)} placeholder={value.merchant_id_configured?`مقدار فعلی: ${value.merchant_id_hint}`:"Merchant ID زرین‌پال"}/></div>{numericKeys.map(([key,label])=><div key={key}><label className="label">{label}</label><input className="input" inputMode="numeric" value={fmt.digits(value[key])} onChange={event=>setValue({...value,[key]:Number(fmt.latinDigits(event.target.value))})}/></div>)}<div><label className="label">نسخه قوانین</label><input className="input" dir="ltr" value={value.terms_version} onChange={event=>setValue({...value,terms_version:event.target.value})}/></div><div><label className="label">لینک قوانین</label><input className="input" dir="ltr" value={value.terms_url} onChange={event=>setValue({...value,terms_url:event.target.value})}/></div><label className="flex items-center gap-2 md:col-span-2"><input type="checkbox" checked={value.automatic_discounts_enabled} onChange={event=>setValue({...value,automatic_discounts_enabled:event.target.checked})}/>تخفیف خودکار فعال باشد</label><div className="flex gap-2 md:col-span-2"><button className="btn">ذخیره</button><button type="button" className="btn-ghost" onClick={async()=>{try{const result=await request<{ok:boolean;mode:string}>("/v1/admin/commerce/settings/test",{method:"POST"});setNotice(`تنظیمات درگاه معتبر است (${result.mode}).`);}catch(reason){setError((reason as Error).message);}}}>آزمایش تنظیمات</button></div></section></form>;
}
