import { useEffect, useState } from "react";
import { fmt, request } from "../api";
import { useAuth } from "../auth";
import { Empty, ErrorBox, Loading, Pagination } from "../components/Widgets";
import type { Page } from "../types";

interface StaffRow { id:string; email:string; role:string; two_factor_enabled:boolean; disabled_at:string|null; created_at:string }

export default function Staff(){
  const limit=25;const[offset,setOffset]=useState(0);const {session}=useAuth();const[page,setPage]=useState<Page<StaffRow>|null>(null);const[error,setError]=useState<string|null>(null);const[form,setForm]=useState({email:"",password:"",role:"support",current_password:"",totp_code:""});
  async function load(){try{setPage(await request<Page<StaffRow>>(`/v1/admin/staff?offset=${offset}&limit=${limit}`));}catch(reason){setError((reason as Error).message);}}
  useEffect(()=>{void load();},[offset]);
  const rows=page?.items??null;
  async function create(event:React.FormEvent){event.preventDefault();try{await request("/v1/admin/staff",{method:"POST",body:{...form,totp_code:form.totp_code||null}});setForm({...form,email:"",password:""});await load();}catch(reason){setError((reason as Error).message);}}
  async function toggle(item:StaffRow){const password=window.prompt("رمز فعلی خودتان را وارد کنید");if(!password)return;const code=window.prompt("کد دومرحله‌ای، در صورت فعال بودن");try{await request(`/v1/admin/staff/${item.id}/${item.disabled_at?'activate':'disable'}`,{method:"POST",body:{current_password:password,totp_code:code||null}});await load();}catch(reason){setError((reason as Error).message);}}
  async function sensitive(item:StaffRow, action:"reset-password"|"reset-totp"){const current=window.prompt("رمز فعلی خودتان را وارد کنید");if(!current)return;const code=window.prompt("کد دومرحله‌ای، در صورت فعال بودن");const password=action==="reset-password"?window.prompt("رمز جدید کاربر را وارد کنید"):null;if(action==="reset-password"&&!password)return;try{await request(`/v1/admin/staff/${item.id}/${action}`,{method:"POST",body:{current_password:current,totp_code:code||null,...(password?{password}:{})}});await load();}catch(reason){setError((reason as Error).message);}}
  return <div className="space-y-4"><div><h1 className="text-2xl font-bold">کاربران ادمین</h1><p className="mt-1 text-sm text-slate-500">همه نقش‌های staff دسترسی کامل دارند؛ عملیات حساس نیازمند احراز مجدد است.</p></div><ErrorBox message={error}/><form className="card grid gap-3 md:grid-cols-3" onSubmit={create}><input className="input" type="email" dir="ltr" placeholder="ایمیل" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/><input className="input" type="password" dir="ltr" placeholder="رمز کاربر جدید" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} minLength={8} required/><select className="input" value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="support">پشتیبانی</option><option value="super_admin">مدیر کل</option></select><input className="input" type="password" dir="ltr" placeholder="رمز فعلی شما" value={form.current_password} onChange={event=>setForm({...form,current_password:event.target.value})} required/><input className="input" dir="ltr" inputMode="numeric" placeholder="کد دومرحله‌ای شما" value={form.totp_code} onChange={event=>setForm({...form,totp_code:fmt.latinDigits(event.target.value)})}/><button className="btn">ایجاد کاربر</button></form><div className="card overflow-x-auto">{!rows?<Loading/>:rows.length===0?<Empty/>:<table className="table"><thead><tr><th>ایمیل</th><th>نقش</th><th>ورود دومرحله‌ای</th><th>وضعیت</th><th>ایجاد</th><th/></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td dir="ltr">{item.email}</td><td>{item.role}</td><td>{item.two_factor_enabled?'فعال':'غیرفعال'}</td><td>{item.disabled_at?'غیرفعال':'فعال'}</td><td>{fmt.date(item.created_at)}</td><td className="space-x-2 space-x-reverse">{item.id!==session?.staffId?<button className="btn-ghost text-xs" onClick={()=>void toggle(item)}>{item.disabled_at?'فعال‌سازی':'غیرفعال‌سازی'}</button>:<span className="text-xs text-slate-400">حساب شما</span>}<button className="btn-ghost text-xs" onClick={()=>void sensitive(item,"reset-password")}>بازنشانی رمز</button>{item.two_factor_enabled?<button className="btn-ghost text-xs text-rose-700" onClick={()=>void sensitive(item,"reset-totp")}>حذف ورود دومرحله‌ای</button>:null}</td></tr>)}</tbody></table>}{page?<Pagination offset={offset} limit={limit} total={page.total} onChange={setOffset}/>:null}</div></div>;
}
