import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { chart } from "@cbi/web-shared/theme";
import { fmt, query, request } from "../api";
import { isOperator, useAuth } from "../auth";
import { ErrorBox, Loading, Pagination } from "../components/Widgets";
import type { KpiDashboard, RateMetric } from "../types";

const FUNNEL: Record<string, string> = { all_calls: "کل تماس‌ها", effective: "تماس مؤثر", qualified: "واجد شرایط", interested: "علاقه‌مند", follow_up: "پیگیری", proposal: "پیشنهاد", won: "فروش", lost: "ازدست‌رفته" };
const ACTIONS: Record<string, string> = { hot_opportunity: "فرصت داغ بدون پیگیری", overdue_follow_up: "پیگیری عقب‌افتاده", needs_review: "نیازمند بازبینی", kpi_decline: "افت معنادار KPI", objection_surge: "افزایش ناگهانی اعتراض" };
const pct = (metric: RateMetric) => metric.value == null ? "—" : `${fmt.decimal(metric.value)}٪`;
const delta = (metric: RateMetric) => metric.change == null ? "" : ` · ${metric.change > 0 ? "+" : ""}${fmt.decimal(metric.change)} واحد نسبت به دوره قبل`;

function Card({ title, value, hint, alert }: { title: string; value: string; hint?: string; alert?: boolean }) {
  return <div className={`rounded-2xl border p-4 ${alert ? "border-rose-100 bg-rose-50" : "border-brand-100 bg-brand-50/60"}`}><p className="text-xs text-slate-500">{title}</p><p className="mt-2 text-2xl font-black">{value}</p>{hint ? <p className="mt-1 text-xs text-slate-500">{hint}</p> : null}</div>;
}

function Breakdown({ title, rows }: { title: string; rows: Array<[string, number]> }) {
  const max = Math.max(1, ...rows.map((row) => row[1]));
  return <section className="card"><h2 className="mb-4 font-bold">{title}</h2><div className="space-y-3">{rows.length ? rows.map(([label, count]) => <div key={label}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><span>{fmt.int(count)}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-brand-500" style={{ width: `${count * 100 / max}%` }} /></div></div>) : <p className="text-sm text-slate-400">داده کافی وجود ندارد.</p>}</div></section>;
}

export default function Analytics() {
  const tableLimit = 25;
  const [operatorOffset, setOperatorOffset] = useState(0);
  const [campaignOffset, setCampaignOffset] = useState(0);
  const { session } = useAuth();
  const operator = isOperator(session?.role);
  const [days, setDays] = useState(30);
  const [direction, setDirection] = useState("");
  const [campaign, setCampaign] = useState("");
  const [source, setSource] = useState("");
  const [intent, setIntent] = useState("");
  const [certainty, setCertainty] = useState("");
  const [team, setTeam] = useState("");
  const [operatorId, setOperatorId] = useState("");
  const [data, setData] = useState<KpiDashboard | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { setOperatorOffset(0); setCampaignOffset(0); }, [days, direction, campaign, source, intent, certainty, team, operatorId]);
  useEffect(() => {
    setData(null); setError(null);
    const from = new Date(Date.now() - days * 86400000).toISOString();
    request<KpiDashboard>(`/v1/kpi/dashboard${query({ from, direction, campaign_id: campaign, source, intent, certainty, team_id: team, operator_id: operatorId, operator_offset: operatorOffset, campaign_offset: campaignOffset, table_limit: tableLimit })}`).then(setData).catch((reason) => setError((reason as Error).message));
  }, [days, direction, campaign, source, intent, certainty, team, operatorId, operatorOffset, campaignOffset]);
  if (error) return <ErrorBox message={error} />;
  if (!data) return <Loading />;
  const c = data.cards;
  const funnel = data.funnel.map((item) => ({ ...item, name: FUNNEL[item.key] ?? item.key }));
  return <div className="space-y-5" dir="rtl">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-black">{operator ? "مرکز عملکرد من" : "مرکز تصمیم‌گیری فروش"}</h1><p className="mt-1 text-sm text-slate-500">نتیجه تجاری، کیفیت اجرا و اقدام‌های ضروری</p></div><div className="flex gap-2">{[[7, "۷ روز"], [30, "۳۰ روز"], [90, "۹۰ روز"]].map(([value, label]) => <button key={value} className={days === value ? "btn" : "btn-ghost"} onClick={() => setDays(Number(value))}>{label}</button>)}</div></header>
    <section className="card grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select className="input" value={direction} onChange={(e) => setDirection(e.target.value)}><option value="">همه جهت‌ها</option>{data.filters.directions.map((item) => <option key={item} value={item}>{item === "inbound" ? "ورودی" : item === "outbound" ? "خروجی" : item}</option>)}</select><select className="input" value={campaign} onChange={(e) => setCampaign(e.target.value)}><option value="">همه کمپین‌ها</option>{data.filters.campaigns.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={source} onChange={(e) => setSource(e.target.value)}><option value="">همه منابع</option>{data.filters.sources.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={intent} onChange={(e) => setIntent(e.target.value)}><option value="">همه قصدها</option>{data.filters.intents.map((item) => <option key={item}>{item}</option>)}</select><select className="input" value={certainty} onChange={(e) => setCertainty(e.target.value)}><option value="">همه سطوح اطمینان</option>{data.filters.certainties.map((item) => <option key={item}>{item}</option>)}</select>{!operator ? <><select className="input" value={team} onChange={(e) => { setTeam(e.target.value); setOperatorId(""); }}><option value="">همه تیم‌ها</option>{data.filters.teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="input" value={operatorId} onChange={(e) => { setOperatorId(e.target.value); setTeam(""); }}><option value="">همه اپراتورها</option>{data.filters.operators.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></> : null}</section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card title="کل تماس" value={fmt.int(c.total_calls)} hint={`${fmt.int(c.effective_calls)} تماس مؤثر`} /><Card title="فرصت فروش" value={fmt.int(c.opportunities)} hint={`${fmt.int(c.probable_opportunities)} محتمل · ${pct(c.probable_opportunity_rate)}${delta(c.probable_opportunity_rate)}`} /><Card title="فروش صریح AI" value={fmt.int(c.explicit_wins)} hint={`نرخ برد ${pct(c.ai_win_rate)}${delta(c.ai_win_rate)}`} /><Card title="پوشش نتیجه" value={pct(c.outcome_coverage)} hint={`${fmt.int(c.unknown_outcomes)} نامشخص${delta(c.outcome_coverage)}`} /><Card title="فرصت داغ بی‌پیگیری" value={fmt.int(c.hot_unassigned)} alert={c.hot_unassigned > 0} /></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="تبدیل رسمی CRM" value={pct(c.crm_conversion_rate)} hint={`${fmt.int(c.crm_conversion_rate.numerator)} برد قطعی${delta(c.crm_conversion_rate)}`} /><Card title="ارزش فروش" value={c.currency ? `${fmt.int(c.revenue)} ${c.currency}` : "—"} /><Card title="میانگین کیفیت" value={c.quality_score == null ? "—" : fmt.decimal(c.quality_score)} /><Card title="پیگیری در SLA" value={pct(c.follow_up_sla_rate)} hint={`${fmt.int(c.follow_up_sla_rate.numerator)} از ${fmt.int(c.follow_up_sla_rate.denominator)}${delta(c.follow_up_sla_rate)}`} /></div>
    <section className="card"><div className="mb-4 flex justify-between"><h2 className="font-bold">قیف فروش تخمینی AI</h2><span className="text-xs text-amber-700">نتیجه CRM جداگانه محاسبه می‌شود</span></div><div className="h-80"><ResponsiveContainer><BarChart data={funnel}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" interval={0} /><YAxis orientation="right" allowDecimals={false} tickFormatter={fmt.int} /><Tooltip formatter={(value) => fmt.int(Number(value))} /><Bar dataKey="count" name="تعداد" fill={chart.primary} radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="grid gap-2 md:grid-cols-4">{funnel.map((item) => <div key={item.key} className="rounded-xl bg-slate-50 p-3 text-xs"><strong>{item.name}</strong><p className="mt-1 text-slate-500">عبور {item.pass_rate == null ? "—" : `${fmt.decimal(item.pass_rate)}٪`} · ریزش {item.drop_rate == null ? "—" : `${fmt.decimal(item.drop_rate)}٪`}</p></div>)}</div></section>
    <div className="grid gap-4 lg:grid-cols-2"><Breakdown title="اعتراض‌های پرتکرار" rows={data.breakdowns.objections} /><Breakdown title="محصولات و خدمات" rows={data.breakdowns.products} /><Breakdown title="موضوعات پرتکرار" rows={data.breakdowns.topics} /><Breakdown title="دلایل برد و باخت" rows={data.breakdowns.win_loss_reasons} /></div>
    {operator ? <div className="grid gap-4 md:grid-cols-2"><section className="card"><h2 className="mb-4 font-bold text-emerald-700">سه نقطه قوت من</h2><div className="space-y-3">{data.coaching.strengths.map((item) => <Link key={item.title} to={`/calls/${item.call_id}`} className="block rounded-xl bg-emerald-50 p-3"><div className="flex justify-between"><strong>{item.title}</strong><span>{fmt.decimal(item.average)}</span></div>{item.evidence ? <p className="mt-2 text-xs text-slate-600">{item.evidence}</p> : null}</Link>)}</div></section><section className="card"><h2 className="mb-4 font-bold text-amber-700">سه اقدام پیشنهادی</h2><div className="space-y-3">{data.coaching.improvements.map((item) => <Link key={item.title} to={`/calls/${item.call_id}`} className="block rounded-xl bg-amber-50 p-3"><div className="flex justify-between"><strong>بهبود {item.title}</strong><span>{fmt.decimal(item.average)}</span></div>{item.evidence ? <p className="mt-2 text-xs text-slate-600">شاهد: {item.evidence}</p> : null}</Link>)}</div></section></div> : null}
    {!operator ? <section className="card overflow-x-auto"><h2 className="mb-4 font-bold">عملکرد اپراتورها</h2><table className="table min-w-[720px]"><thead><tr><th>اپراتور</th><th>تماس</th><th>فرصت</th><th>فروش</th><th>تبدیل</th><th>کیفیت</th><th>سهم صحبت</th><th>نمونه</th></tr></thead><tbody>{data.operators.map((item) => <tr key={item.operator_id}><td>{item.operator_label}</td><td>{fmt.int(item.calls)}</td><td>{fmt.int(item.opportunities)}</td><td>{fmt.int(item.wins)}</td><td>{pct(item.conversion)}</td><td>{item.quality_score == null ? "—" : fmt.decimal(item.quality_score)}</td><td>{item.agent_talk_ratio == null ? "—" : `${fmt.decimal(item.agent_talk_ratio)}٪`}</td><td className={item.sample_sufficient ? "text-emerald-700" : "text-amber-700"}>{item.sample_sufficient ? "کافی" : "ناکافی"}</td></tr>)}</tbody></table><Pagination page={Math.floor(operatorOffset/tableLimit)+1} hasPrevious={operatorOffset>0} hasNext={operatorOffset+tableLimit<data.operators_total} total={data.operators_total} onPrevious={()=>setOperatorOffset(Math.max(0,operatorOffset-tableLimit))} onNext={()=>setOperatorOffset(operatorOffset+tableLimit)}/></section> : null}
    {!operator ? <section className="card overflow-x-auto"><h2 className="mb-4 font-bold">کمپین‌ها و منابع</h2><table className="table min-w-[600px]"><thead><tr><th>کمپین / منبع</th><th>تماس</th><th>فرصت</th><th>فروش</th><th>نرخ برد AI</th></tr></thead><tbody>{data.breakdowns.campaigns.map((item) => <tr key={item.key}><td>{item.key === "unknown" ? "منبع نامشخص" : item.key}</td><td>{fmt.int(item.calls)}</td><td>{fmt.int(item.opportunities)}</td><td>{fmt.int(item.wins)}</td><td>{pct(item.conversion)}</td></tr>)}</tbody></table><Pagination page={Math.floor(campaignOffset/tableLimit)+1} hasPrevious={campaignOffset>0} hasNext={campaignOffset+tableLimit<data.breakdowns.campaigns_total} total={data.breakdowns.campaigns_total} onPrevious={()=>setCampaignOffset(Math.max(0,campaignOffset-tableLimit))} onNext={()=>setCampaignOffset(campaignOffset+tableLimit)}/></section> : null}
    <section className="card"><div className="mb-4 flex justify-between"><h2 className="font-bold">مرکز اقدام</h2><span className="rounded-full bg-rose-50 px-3 py-1 text-xs font-bold text-rose-700">{fmt.int(data.actions.length)} مورد</span></div><div className="grid gap-3 md:grid-cols-2">{data.actions.length ? data.actions.map((item, index) => { const content = <><div className="flex justify-between"><strong>{ACTIONS[item.type] ?? item.type}</strong><span className={item.severity === "high" ? "text-xs text-rose-700" : "text-xs text-amber-700"}>{item.severity === "high" ? "فوری" : "بازبینی"}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{item.title}</p></>; return item.call_id ? <Link key={`${item.call_id}-${index}`} to={`/calls/${item.call_id}`} className="rounded-xl border border-slate-200 p-4 hover:border-brand-300 hover:bg-brand-50">{content}</Link> : <div key={`${item.type}-${index}`} className="rounded-xl border border-slate-200 p-4">{content}</div>; }) : <p className="text-sm text-emerald-700">اقدام فوری باقی نمانده است.</p>}</div></section>
  </div>;
}
