import { useEffect, useState } from "react";
import JalaliDatePicker from "@cbi/web-shared/components/JalaliDatePicker";
import ToggleSwitch from "@cbi/web-shared/components/ToggleSwitch";
import { fmt, request } from "../api";
import { ErrorBox, Loading, Pagination } from "../components/Widgets";
import type { Page, User } from "../types";

interface Settings { follow_up_sla_hours: number; minimum_sample_size: number; probable_confidence_threshold: number; hot_opportunity_threshold: number; operator_team_comparison_visible: boolean; taxonomy_version: number; funnel_stages: string[]; objection_taxonomy: string[] }
interface Team { id: string; name: string; active: boolean; members: Array<{ id: string; name: string; valid_from: string }> }
interface Goal { id: string; team_id: string | null; metric: string; target_value: number; valid_from: string; valid_to: string }

export default function KpiSettings() {
  const limit = 25;
  const [goalOffset, setGoalOffset] = useState(0);
  const [goalTotal, setGoalTotal] = useState(0);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [version, setVersion] = useState(0);
  const [teams, setTeams] = useState<Team[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [goals, setGoals] = useState<Goal[]>([]);
  const [teamName, setTeamName] = useState("");
  const [member, setMember] = useState({ team_id: "", operator_id: "" });
  const [goal, setGoal] = useState({ metric: "conversion_rate", target_value: 20, team_id: "", valid_from: new Date().toISOString().slice(0, 10), valid_to: new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10) });
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState<string | null>(null);
  async function load() {
    try {
      const [config, teamRows, userRows, goalRows] = await Promise.all([request<{ version: number; settings: Settings }>("/v1/kpi/settings"), request<Team[]>("/v1/kpi/teams"), request<Page<User>>("/v1/auth/users?limit=100"), request<Page<Goal>>(`/v1/kpi/goals?limit=${limit}&offset=${goalOffset}`)]);
      setVersion(config.version); setSettings(config.settings); setTeams(teamRows); setUsers(userRows.items.filter((item) => item.role === "operator")); setGoals(goalRows.items); setGoalTotal(goalRows.total);
    } catch (reason) { setError((reason as Error).message); }
  }
  useEffect(() => { void load(); }, [goalOffset]);
  async function save() { if (!settings) return; try { const row = await request<{ version: number; settings: Settings }>("/v1/kpi/settings", { method: "PUT", body: settings }); setVersion(row.version); setSettings(row.settings); setSaved("تنظیمات KPI ثبت شد."); } catch (reason) { setError((reason as Error).message); } }
  async function createTeam(event: React.FormEvent) { event.preventDefault(); await request("/v1/kpi/teams", { method: "POST", body: { name: teamName } }); setTeamName(""); await load(); }
  async function assign(event: React.FormEvent) { event.preventDefault(); await request(`/v1/kpi/teams/${member.team_id}/members`, { method: "POST", body: { operator_id: member.operator_id, valid_from: new Date().toISOString() } }); await load(); }
  async function createGoal(event: React.FormEvent) { event.preventDefault(); await request("/v1/kpi/goals", { method: "POST", body: { ...goal, target_value: Number(goal.target_value), team_id: goal.team_id || null, valid_from: new Date(goal.valid_from).toISOString(), valid_to: new Date(goal.valid_to).toISOString() } }); await load(); }
  if (!settings) return error ? <ErrorBox message={error} /> : <Loading />;
  return <div className="space-y-5" dir="rtl"><header><h1 className="text-xl font-black">تنظیمات KPI فروش</h1><p className="mt-1 text-sm text-slate-500">نسخه {fmt.int(version)} · تمام تغییرات نسخه‌دار و قابل ممیزی هستند.</p></header>{error ? <ErrorBox message={error} /> : null}
    <section className="card space-y-4"><h2 className="font-bold">آستانه‌ها و سیاست نمایش</h2><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm">SLA پیگیری (ساعت)<input className="input mt-1" type="number" value={settings.follow_up_sla_hours} onChange={(e) => setSettings({ ...settings, follow_up_sla_hours: Number(e.target.value) })} /></label><label className="text-sm">حداقل نمونه<input className="input mt-1" type="number" value={settings.minimum_sample_size} onChange={(e) => setSettings({ ...settings, minimum_sample_size: Number(e.target.value) })} /></label><label className="text-sm">اطمینان فرصت محتمل<input className="input mt-1" type="number" step="0.05" min="0" max="1" value={settings.probable_confidence_threshold} onChange={(e) => setSettings({ ...settings, probable_confidence_threshold: Number(e.target.value) })} /></label><label className="text-sm">آستانه فرصت داغ<input className="input mt-1" type="number" step="0.05" min="0" max="1" value={settings.hot_opportunity_threshold} onChange={(e) => setSettings({ ...settings, hot_opportunity_threshold: Number(e.target.value) })} /></label><label className="text-sm">نسخه taxonomy<input className="input mt-1" type="number" min="1" value={settings.taxonomy_version} onChange={(e) => setSettings({ ...settings, taxonomy_version: Number(e.target.value) })} /></label><label className="text-sm md:col-span-2">مراحل قیف با ویرگول<input className="input mt-1" dir="ltr" value={settings.funnel_stages.join(",")} onChange={(e) => setSettings({ ...settings, funnel_stages: e.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /></label><label className="text-sm md:col-span-2">taxonomy اعتراض‌ها با ویرگول<input className="input mt-1" dir="ltr" value={settings.objection_taxonomy.join(",")} onChange={(e) => setSettings({ ...settings, objection_taxonomy: e.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /></label></div><ToggleSwitch checked={settings.operator_team_comparison_visible} onChange={(checked) => setSettings({ ...settings, operator_team_comparison_visible: checked })} label="نمایش هدف تیم به اپراتور" labelClassName="text-sm" /><p className="text-xs text-slate-500">کلید اتصال CRM در بخش حساب و webhook امضاشده در همان بخش مدیریت می‌شود.</p><div className="flex items-center gap-3"><button className="btn" onClick={() => void save()}>ثبت نسخه جدید</button>{saved ? <span className="text-sm text-emerald-700">{saved}</span> : null}</div></section>
    <section className="card space-y-4"><h2 className="font-bold">تیم‌ها و اعضا</h2><form className="flex gap-2" onSubmit={(e) => void createTeam(e)}><input className="input" value={teamName} onChange={(e) => setTeamName(e.target.value)} placeholder="نام تیم جدید" required minLength={2} /><button className="btn">ایجاد تیم</button></form><form className="grid gap-2 md:grid-cols-3" onSubmit={(e) => void assign(e)}><select className="input" value={member.team_id} onChange={(e) => setMember({ ...member, team_id: e.target.value })} required><option value="">انتخاب تیم</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="input" value={member.operator_id} onChange={(e) => setMember({ ...member, operator_id: e.target.value })} required><option value="">انتخاب اپراتور</option>{users.map((item) => <option key={item.id} value={item.id}>{item.email}</option>)}</select><button className="btn">تخصیص زمان‌دار</button></form><div className="grid gap-3 md:grid-cols-2">{teams.map((item) => <div key={item.id} className="rounded-xl border p-3"><strong>{item.name}</strong><p className="mt-2 text-xs text-slate-500">{item.members.length ? item.members.map((memberRow) => memberRow.name).join("، ") : "بدون عضو"}</p></div>)}</div></section>
    <section className="card space-y-4"><h2 className="font-bold">اهداف سازمان و تیم</h2><form className="grid gap-2 md:grid-cols-5" onSubmit={(e) => void createGoal(e)}><select className="input" value={goal.metric} onChange={(e) => setGoal({ ...goal, metric: e.target.value })}><option value="conversion_rate">نرخ تبدیل</option><option value="quality_score">امتیاز کیفیت</option><option value="follow_up_sla_rate">پیگیری در SLA</option></select><input className="input" type="number" value={goal.target_value} onChange={(e) => setGoal({ ...goal, target_value: Number(e.target.value) })} /><select className="input" value={goal.team_id} onChange={(e) => setGoal({ ...goal, team_id: e.target.value })}><option value="">کل سازمان</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><JalaliDatePicker value={goal.valid_from} onChange={(value) => setGoal({ ...goal, valid_from: value })} placeholder="تاریخ شروع" /><JalaliDatePicker value={goal.valid_to} onChange={(value) => setGoal({ ...goal, valid_to: value })} placeholder="تاریخ پایان" /><button className="btn md:col-span-5">ثبت هدف</button></form><div className="overflow-x-auto"><table className="table"><thead><tr><th>معیار</th><th>دامنه</th><th>هدف</th><th>شروع</th><th>پایان</th></tr></thead><tbody>{goals.map((item) => <tr key={item.id}><td>{item.metric}</td><td>{teams.find((team) => team.id === item.team_id)?.name ?? "سازمان"}</td><td>{fmt.decimal(item.target_value)}</td><td>{fmt.date(item.valid_from)}</td><td>{fmt.date(item.valid_to)}</td></tr>)}</tbody></table><Pagination page={Math.floor(goalOffset/limit)+1} hasPrevious={goalOffset>0} hasNext={goalOffset+limit<goalTotal} total={goalTotal} onPrevious={()=>setGoalOffset(Math.max(0,goalOffset-limit))} onNext={()=>setGoalOffset(goalOffset+limit)}/></div></section>
  </div>;
}
